### ISSUE TITLE
tendrl-performance-monitoring not starting with pkg_resources.DistributionNotFound: urllib error

### ISSUE THREAD

**Issue by dahorak** [Tendrl/performance-monitoring#58]
With recent version of `tendrl-performance-monitoring` (`1.2-02_27_2017_14_36_18.noarch`) is not possible to start the `tendrl-performance-monitoring` service.
```
# systemctl status tendrl-performance-monitoring
● tendrl-performance-monitoring.service - Daemon to manage tendrl monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-performance-monitoring.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2017-02-27 13:10:18 UTC; 6min ago
  Process: 20274 ExecStart=/usr/bin/tendrl-performance-monitoring (code=exited, status=1/FAILURE)
 Main PID: 20274 (code=exited, status=1/FAILURE)

Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-performance-monitoring.service: main process exited, code=exited, status=1/FAILURE
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: Unit tendrl-performance-monitoring.service entered failed state.
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-performance-monitoring.service failed.
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-performance-monitoring.service holdoff time over, scheduling restart.
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: start request repeated too quickly for tendrl-performance-monitoring.service
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: Failed to start Daemon to manage tendrl monitoring.
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: Unit tendrl-performance-monitoring.service entered failed state.
Feb 27 13:10:18 mkudlej-usm5-mon1.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-performance-monitoring.service failed.
```

Output from `journalctl -xe`:
```
Feb 27 13:10:17 mon1.example.com systemd[1]: Starting Daemon to manage tendrl monitoring...
-- Subject: Unit tendrl-performance-monitoring.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tendrl-performance-monitoring.service has begun starting up.
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: Traceback (most recent call last):
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: File "/usr/bin/tendrl-performance-monitoring", line 5, in <module>
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: from pkg_resources import load_entry_point
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: working_set.require(__requires__)
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: needed = self.resolve(parse_requirements(requirements))
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: raise DistributionNotFound(req)
Feb 27 13:10:17 mon1.example.com tendrl-performance-monitoring[20266]: pkg_resources.DistributionNotFound: urllib
Feb 27 13:10:17 mon1.example.com systemd[1]: tendrl-performance-monitoring.service: main process exited, code=exited, status=1/FAILURE
Feb 27 13:10:17 mon1.example.com systemd[1]: Unit tendrl-performance-monitoring.service entered failed state.
Feb 27 13:10:17 mon1.example.com systemd[1]: tendrl-performance-monitoring.service failed.
Feb 27 13:10:17 mon1.example.com systemd[1]: tendrl-performance-monitoring.service holdoff time over, scheduling restart.
Feb 27 13:10:17 mon1.example.com systemd[1]: Cannot add dependency job for unit microcode.service, ignoring: Unit is not loaded properly: Invalid argument.
Feb 27 13:10:17 mon1.example.com systemd[1]: Started Daemon to manage tendrl monitoring.
-- Subject: Unit tendrl-performance-monitoring.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tendrl-performance-monitoring.service has finished starting up.
-- 
-- The start-up result is done.
```
Versions of other Tendrl components:
```
# rpm -qa | grep tendrl
tendrl-commons-1.2-02_27_2017_04_54_07.noarch
tendrl-node-agent-1.2-02_27_2017_00_01_02.noarch
tendrl-performance-monitoring-1.2-02_27_2017_14_36_18.noarch
```

**Comment by dahorak** [comment]
It seems to be quite recent issue, because it works with version `tendrl-performance-monitoring-1.2-02_27_2017_03_02_02.noarch`.

**Comment by dahorak** [comment]
Package `python-urllib3` is installed:
```
# rpm -q python-urllib3
python-urllib3-1.10.2-2.el7_1.noarch
```

**Comment by sankarshanmukhopadhyay** [comment]
@anmolbabu @shtripat  might want to check this one.

**Comment by dahorak** [comment]
The problem seems to be with `requires.txt` file, because the version from package contain `urllib`:
```
# cat /usr/lib/python2.7/site-packages/tendrl_performance_monitoring-1.2-py2.7.egg-info/requires.txt
carbon>=0.9.15
whisper>=0.9.15
graphite-web>=0.9.15
flask>=0.10.1
python-etcd
six
PyYAML
gevent
urllib
```
while the version from this git contains correctly `urllib3` (https://github.com/Tendrl/performance-monitoring/blob/master/requirements.txt)

**Comment by sankarshanmukhopadhyay** [comment]
adding @TimothyAsir to this.

**Comment by mbukatov** [comment]
I believe that this issue is caused by hacks in `setup.py` which fetches content of requirements.txt into install_requires of setup.py. We should not do that and this issue is another evidence of maintenance burden such hacks create for us.

**Comment by mbukatov** [comment]
Here is the evidence.

Let's generate sdist tarball on current master:

```
$ cd ~/projects/tendrl.org/tendrl-performance-monitoring
$ python2 setup.py sdist
```

Then look for files with requirements there:

```
$ tar tf dist/tendrl-performance-monitoring-1.2.tar.gz | grep require
tendrl-performance-monitoring-1.2/tendrl_performance_monitoring.egg-info/requires.txt
tendrl-performance-monitoring-1.2/requirements.txt
```

And finally, check it's content:

```
$ tar xf dist/tendrl-performance-monitoring-1.2.tar.gz tendrl-performance-monitoring-1.2/requirements.txt -O
# The order of packages is significant, because pip processes them in the order
# of appearance. Changing the order has an impact on the overall integration
# process, which may cause wedges in the gate later.

carbon>=0.9.15
whisper>=0.9.15
graphite-web>=0.9.15
flask>=0.10.1
python-etcd
six
PyYAML
gevent
urllib3
$ tar xf dist/tendrl-performance-monitoring-1.2.tar.gz tendrl-performance-monitoring-1.2/tendrl_performance_monitoring.egg-info/requires.txt -O
carbon>=0.9.15
whisper>=0.9.15
graphite-web>=0.9.15
flask>=0.10.1
python-etcd
six
PyYAML
gevent
urllib
```

And as we can see, the issue is already there, caused by unnecessary hacks in
setup.py.

**Comment by mbukatov** [comment]
I'm going to address this during my upcoming packaging pull requests by removing that hack from setup.py. Right now, I'm focusing on tendrl-commons.

**Comment by sankarshanmukhopadhyay** [comment]
Since the fix is merged, I'd request the reporter to check the builds, when available and update this issue.

**Comment by dahorak** [comment]
Tested with version `tendrl-performance-monitoring-1.2-02_28_2017_13_18_20.noarch`.
The `requires.txt` file correctly contains `urllib3`:
```
# cat /usr/lib/python2.7/site-packages/tendrl_performance_monitoring-1.2-py2.7.egg-info/requires.txt
carbon>=0.9.15
whisper>=0.9.15
graphite-web>=0.9.15
flask>=0.10.1
python-etcd
six
PyYAML
gevent
urllib3
```
And it is possible to start `tendrl-performance-monitoring` service:
```# systemctl status tendrl-performance-monitoring
● tendrl-performance-monitoring.service - Daemon to manage tendrl monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-performance-monitoring.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-02-28 12:37:59 UTC; 1h 56min ago
 Main PID: 32133 (tendrl-performa)
   CGroup: /system.slice/tendrl-performance-monitoring.service
           ├─32133 /usr/bin/python /usr/bin/tendrl-performance-monitoring
           ├─32208 /usr/bin/python /usr/bin/tendrl-performance-monitoring
           └─32209 /usr/bin/python /usr/bin/tendrl-performance-monitoring
```
