### ISSUE TITLE
wrong port parameter

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/performance-monitoring#66]
There is wrong type of port parameter for Etcd client in performance monitoring service.

```
$ /usr/bin/tendrl-performance-monitoring
2017-03-08T10:09:46+0000 - /usr/lib/python2.7/site-packages/urllib3/connectionpool.py - connectionpool.py:203 -            _new_conn() - INFO - Starting new HTTP connection (1): mkudlej-usm1-server.usmqe.lab.eng.brq.redhat.com
Traceback (most recent call last):
  File "/usr/bin/tendrl-performance-monitoring", line 9, in <module>
    load_entry_point('tendrl-performance-monitoring==1.2.1', 'console_scripts', 'tendrl-performance-monitoring')()
  File "/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/manager/__init__.py", line 165, in main
    tendrl_perf_manager = TendrlPerformanceManager()
  File "/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/manager/__init__.py", line 132, in __init__
    self.configure_monitoring = ConfigureMonitoring()
  File "/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/configure/configure_monitoring.py", line 40, in __init__
    self.init_monitoring()
  File "/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/configure/configure_monitoring.py", line 28, in init_monitoring
    self.etcd_orm = etcdobj.Server(etcd_kwargs=etcd_kwargs)
  File "/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", line 126, in __init__
    etcd.Client(**etcd_kwargs))
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 134, in __init__
    self._base_uri = uri(self._protocol, host, port)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 130, in uri
    return '%s://%s:%d' % (protocol, host, port)
TypeError: %d format: a number is required, not unicode
```

**Comment by sankarshanmukhopadhyay** [comment]
https://github.com/Tendrl/usmqe-tests/wiki states there is a PR (proposed patch) for this? Could we have that reviewed, merged and move forward from here?

**Comment by anmolbabu** [comment]
@sankarshanmukhopadhyay It is fixed and merged

**Comment by mkudlej** [comment]
This seems to be fixed in 
```
tendrl-commons-1.2.1-03_23_2017_12_30_14.noarch
tendrl-node-agent-1.2.1-03_23_2017_12_32_32.noarch
tendrl-node-monitoring-1.2.1-03_23_2017_00_37_03.noarch
```
