### ISSUE TITLE
graphite not running

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/performance-monitoring#68]
Graphite fails to start.

Used packages:
tendrl-api-httpd-1.2.1-03_09_2017_01_51_04.noarch
tendrl-api-doc-1.2.1-03_09_2017_01_51_04.noarch
tendrl-commons-1.2.1-03_09_2017_05_04_44.noarch
tendrl-api-1.2.1-03_09_2017_01_51_04.noarch
tendrl-dashboard-1.2.1-03_09_2017_04_11_03.noarch
tendrl-performance-monitoring-1.2.1-03_09_2017_03_02_03.noarch

error from tendrl-performance-monitoring log:
```
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/tendrl/performance_monitoring/time_series_db/dbplugins/graphite.py", line 30, in get_metric_stats
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: stats = self.http.request('GET', url, timeout=5)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: **urlopen_kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: return self.urlopen(method, url, **urlopen_kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 161, in urlopen
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: response = conn.urlopen(method, u.request_uri, **kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 617, in urlopen
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: release_conn=release_conn, **response_kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 617, in urlopen
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: release_conn=release_conn, **response_kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 617, in urlopen
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: release_conn=release_conn, **response_kw)
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: _stacktrace=sys.exc_info()[2])
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 271, in increment
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: raise MaxRetryError(_pool, url, error or ResponseError(cause))
bře 09 13:09:11 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com tendrl-performance-monitoring[22560]: MaxRetryError: HTTPConnectionPool(host=u'10.34.108.59', port=10080): Max retries exceeded with url: /render?target=cactiStyle(collectd.fbalak-usm1-gl1_usmqe_lab_eng_brq_redhat_com.df-*.df_complex-used)&format=json (Caused by ProtocolError('Connection aborted.', error(111, 'Connection refused')))
```

**Comment by nthomas-redhat** [comment]
@ltrilety check the firewalld/iptables and selinux
Hope you are following https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference

**Comment by ltrilety** [comment]
@nthomas-redhat firewall.service was not present and iptables was flushed.
```
# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
selinux set to permissive.
```
# getenforce
Permissive
```
And yes, we follow that instructions.

**Comment by anmolbabu** [comment]
@ltrilety Please verify if you are able to access the graphite ui using http://{performance-monitoring-host_ip/fqdn}:10080 manually also please provide me the contents of /etc/httpd/conf.d/graphite-web.conf and please provide the outputs of service carbon-cache status -l and service httpd status -l ..

**Comment by anmolbabu** [comment]
@ltrilety If you are able to manually access graphite ui from the url in previous comment, please confirm that firewalld is stopped on even the nodes and also selinux is set to permissive on all the nodes... And provide me the status of service collectd status -l of the ndoes.

**Comment by ltrilety** [comment]
@anmolbabu I am not able to access graphite using the URL, that was the first place where I noticed that something is wrong. Sorry I should mentioned that in my first comment.
```
# cat /etc/httpd/conf.d/graphite-web.conf
# Graphite Web Basic mod_wsgi vhost

Listen 10080

<VirtualHost *:10080>
    ServerName graphite-web
    DocumentRoot "/usr/share/graphite/webapp"
    ErrorLog /var/log/httpd/graphite-web-error.log
    CustomLog /var/log/httpd/graphite-web-access.log common

    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, OPTIONS"
    Header set Access-Control-Allow-Headers "origin, authorization, accept"
    Header set Access-Control-Allow-Credentials true

    WSGIScriptAlias / /usr/share/graphite/graphite-web.wsgi
    WSGIImportScript /usr/share/graphite/graphite-web.wsgi process-group=%{GLOBAL} application-group=%{GLOBAL}

    <Location "/content/">
        SetHandler None
    </Location>

    Alias /media/ "/usr/lib/python2.7/site-packages/django/contrib/admin/media/"
    <Location "/media/">
        SetHandler None
    </Location>

   <Directory "/usr/share/graphite/">
       <IfModule mod_authz_core.c>
           # Apache 2.4
           Order Deny,Allow
           Allow from all
           Require all granted
       </IfModule>
       <IfModule !mod_authz_core.c>
           # Apache 2.2
           Order Deny,Allow
           Allow from all
           Require all granted
       </IfModule>
   </Directory>
</VirtualHost>
```
```
# systemctl status  -l carbon-cache
● carbon-cache.service - Graphite Carbon Cache
   Loaded: loaded (/usr/lib/systemd/system/carbon-cache.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-03-10 08:11:22 UTC; 49min ago
 Main PID: 22225 (carbon-cache)
   CGroup: /system.slice/carbon-cache.service
           └─22225 /usr/bin/python2 -s /usr/bin/carbon-cache --config=/etc/carbon/carbon.conf --pidfile=/var/run/carbon-cache.pid --logdir=/var/log/carbon/ start

Mar 10 08:11:21 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting Graphite Carbon Cache...
Mar 10 08:11:22 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Started Graphite Carbon Cache.
```
```
# systemctl status -l httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-03-10 08:10:27 UTC; 51min ago
     Docs: man:httpd(8)
           man:apachectl(8)
 Main PID: 21164 (httpd)
   Status: "Total requests: 85; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─  321 /usr/sbin/httpd -DFOREGROUND
           ├─  323 /usr/sbin/httpd -DFOREGROUND
           ├─  326 /usr/sbin/httpd -DFOREGROUND
           ├─  327 /usr/sbin/httpd -DFOREGROUND
           ├─21164 /usr/sbin/httpd -DFOREGROUND
           ├─21165 /usr/sbin/httpd -DFOREGROUND
           ├─21166 /usr/sbin/httpd -DFOREGROUND
           ├─21167 /usr/sbin/httpd -DFOREGROUND
           ├─21168 /usr/sbin/httpd -DFOREGROUND
           └─21169 /usr/sbin/httpd -DFOREGROUND

Mar 10 08:10:27 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting The Apache HTTP Server...
Mar 10 08:10:27 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com httpd[21164]: AH00112: Warning: DocumentRoot [/var/www/tendrl] does not exist
Mar 10 08:10:27 fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com systemd[1]: Started The Apache HTTP Server.
```

BTW firewall is stopped and selinux set to permissive on all nodes.
collectd status from one of the nodes
```
# systemctl status -l collectd
● collectd.service - Collectd statistics daemon
   Loaded: loaded (/usr/lib/systemd/system/collectd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:collectd(1)
           man:collectd.conf(5)
```
FYI collectd can be started. Then following lines can be found in its log
```
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: plugin_dispatch_values: No write callback has been registered. Please load at least one output plugin
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: Filter subsystem: Built-in target `write': Dispatching value to all write plugins failed with status 
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: Available write targets: [none]
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: Available write targets: [none]
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: Available write targets: [none]
Mar 10 09:05:29 fbalak-usm1-gl1.usmqe.lab.eng.brq.redhat.com collectd[17514]: Available write targets: [none]
...
```


Not sure if it's related, but tendrl-node-monitoring seems to have some problem:
```
2017-03-10T09:12:59+0000 - /usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py - __init__.py:153 -                 _run() - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 151, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 111, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 94, in _acceptor
    not in raw_job['node_ids']:
TypeError: argument of type 'NoneType' is not iterable
```

Used packages on nodes:
tendrl-node-monitoring-1.2.1-03_10_2017_00_37_03.noarch
tendrl-gluster-integration-1.2.1-03_10_2017_04_38_03.noarch
tendrl-commons-1.2.1-03_10_2017_04_42_04.noarch
tendrl-node-agent-1.2.1-03_10_2017_00_01_06.noarch

**Comment by anmolbabu** [comment]
@ltrilety So, there was a PR that gave structure to jobs which warranted all the integrations like the monitoring and sds-integrations to follow the new job structure and a PR https://github.com/Tendrl/performance-monitoring/pull/60 was for some reason closed. So this is an issue which caused collectd not to be configured and subbsequently started.

But regarding the graphite not starting, please share the details of your setup on a mail to me and I'll look into it. Meanwhile I'll also try to reproduce this issue..

**Comment by ltrilety** [comment]
The problem was on my side. `httpd` service was not restarted after graphite has been set.
For the `tendrl-node-monitoring` a new issue was created https://github.com/Tendrl/performance-monitoring/issues/70.
