### ISSUE TITLE
tendrl-node-monitoring error

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/performance-monitoring#70]
tendrl-node-monitoring is running but there are following errors in its log:
```
2017-03-13T08:04:50+0000 - /usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py - __init__.py:153 -                 _run() - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 151, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 111, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 94, in _acceptor
    not in raw_job['node_ids']:
TypeError: argument of type 'NoneType' is not iterable
```

Used packages:
tendrl-node-monitoring-1.2.1-03_13_2017_00_37_03.noarch
tendrl-gluster-integration-1.2.1-03_13_2017_04_38_02.noarch
tendrl-commons-1.2.1-03_13_2017_04_42_03.noarch
tendrl-node-agent-1.2.1-03_13_2017_00_01_04.noarch

**Comment by ltrilety** [comment]
In new packages it fails to run https://github.com/Tendrl/performance-monitoring/issues/72

**Comment by anmolbabu** [comment]
@ltrilety  Yes there was a change recently in commons which required #71 These PRs are not yet merged..Even the latest performance-monitoring would not work now...Moreover, the failure attached is likely to be more with latest commons and hence requires #71 ...

**Comment by anmolbabu** [comment]
@ltrilety The PR to fix this has been merged and should be available in latest rpms

**Comment by ltrilety** [comment]
Looks fine, `tendrl-node-monitoring` is running and there seems to be no errors.
