### ISSUE TITLE
tendrl-node-monitoring and tendrl-performance-monitoring services fail

### ISSUE THREAD

**Issue by fbalak** [Tendrl/performance-monitoring#72]
`tendrl-node-monitoring` and `tendrl-performance-monitoring` services are not running and can not be started. This problem occurs on ceph and gluster nodes.

Tested with:
tendrl-node-agent-1.2.1-03_17_2017_04_34_14.noarch
tendrl-commons-1.2.1-03_17_2017_04_50_23.noarch
tendrl-node-monitoring-1.2.1-03_17_2017_00_37_03.noarch
tendrl-api-1.2.1-03_17_2017_01_51_02.noarch
tendrl-performance-monitoring-1.2.1-03_17_2017_03_02_03.noarch

`# systemctl status tendrl-node-monitoring`
● tendrl-node-monitoring.service - Daemon to manage tendrl node monitoring
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-monitoring.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2017-03-17 07:24:42 UTC; 52min ago
  Process: 1215 ExecStart=/usr/bin/tendrl-node-monitoring (code=exited, status=1/FAILURE)
 Main PID: 1215 (code=exited, status=1/FAILURE)

```
Mar 17 07:24:41 localhost.localdomain systemd[1]: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Mar 17 07:24:41 localhost.localdomain systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Mar 17 07:24:41 localhost.localdomain systemd[1]: tendrl-node-monitoring.service failed.
Mar 17 07:24:42 localhost.localdomain systemd[1]: tendrl-node-monitoring.service holdoff time over, scheduling restart.
Mar 17 07:24:42 localhost.localdomain systemd[1]: start request repeated too quickly for tendrl-node-monitoring.service
Mar 17 07:24:42 localhost.localdomain systemd[1]: Failed to start Daemon to manage tendrl node monitoring.
Mar 17 07:24:42 localhost.localdomain systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Mar 17 07:24:42 localhost.localdomain systemd[1]: tendrl-node-monitoring.service failed.
```

`# journalctl _PID=1215`
```
-- Logs begin at Fri 2017-03-17 07:24:14 UTC, end at Fri 2017-03-17 08:18:09 UTC. --
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: Traceback (most recent call last):
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: File "/usr/bin/tendrl-node-monitoring", line 5, in <module>
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: from pkg_resources import load_entry_point
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: working_set.require(__requires__)
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: needed = self.resolve(parse_requirements(requirements))
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: raise DistributionNotFound(req)
Mar 17 07:24:41 localhost.localdomain tendrl-node-monitoring[1215]: pkg_resources.DistributionNotFound: namespaces
```

`# cat /etc/tendrl/node-monitoring/node-monitoring.conf.yaml `
```
---
# Central store etcd port
etcd_port: 2379
# Central store etcd host/ip
etcd_connection: server_hostname
log_cfg_path: /etc/tendrl/node-monitoring/node-monitoring_logging.yaml
tendrl_ansible_exec_file: $HOME/.tendrl/node-monitoring/ansible_exec
logging_socket_path: /var/run/tendrl/message.sock
```

Where `server_hostname` stands for hostname where runs tendrl-api and tendrl-performance-monitoring.

**Comment by anmolbabu** [comment]
@fbalak Yes there was a change recently in commons which required https://github.com/Tendrl/alerting/pull/41 and https://github.com/Tendrl/performance-monitoring/pull/71 These PRs are not yet merged..

**Comment by mkudlej** [comment]
It seems that monitoring service works with:
```
tendrl-commons-1.2.1-03_23_2017_12_30_14.noarch
tendrl-node-agent-1.2.1-03_23_2017_12_32_32.noarch
tendrl-node-monitoring-1.2.1-03_23_2017_00_37_03.noarch
```

**Comment by fbalak** [comment]
ok --> closing
